!!general tools for modules using netcdf functions
!!@author Innocent Souopgui
MODULE nctools
  USE netcdf
  USE general_constant

  IMPLICIT NONE
  INTEGER, PARAMETER :: ip_cnl = 20!!component name length
  INTEGER, PARAMETER :: ip_lnl = 80!!component long name length
CONTAINS
  !!special function use to check netcdf return code
  !!stop the program on error
  SUBROUTINE chkerr(id_flag, fname)
    INTEGER, INTENT(IN) :: id_flag !!code return by call to netcdf function
    CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: fname
    IF (id_flag /= NF90_NOERR) THEN
        PRINT*, '---------------------------------'
        PRINT*, 'NetCDF Error ', id_flag
        PRINT*, nf90_strerror(id_flag )
        IF( PRESENT(fname) )THEN
          PRINT*, 'File Name = '//TRIM(fname)
        ELSE
        END IF
        CALL ABORT
    END IF
  END SUBROUTINE chkerr

  !> \brief generates history string for namelist data file
  !<
  FUNCTION make_ncHistory(ada_text) RESULT(ala_history)
    CHARACTER(LEN=*), INTENT(IN) :: ada_text
    !local variables
    CHARACTER(LEN=ip_fnl) :: ala_history
    CHARACTER(LEN=8)  :: today
    CHARACTER(LEN=10) :: now
    CHARACTER(LEN=5)  :: zone


    CALL date_and_time(today, now, zone)
    WRITE(ala_history, *)&
      'Automatically generated by ', TRIM(ada_text)&
      , ' on ', today(1:4)//'/'//today(5:6)//'/'//today(7:8)&
      , ' at ', now(1:2)//':'//now(3:4)//':'//now(5:6)//now(7:10), ' GMT', zone
  END FUNCTION make_ncHistory

END MODULE nctools
